appcenter/blueprints/app_center/forms.py
from flask_wtf import Form
from wtforms import StringField, TextAreaField, HiddenField
from wtforms.validators import DataRequired, Optional, Length, URL

class AddDocumentForm(Form):
    name = StringField("Document Name", validators=[DataRequired(), Length(max=255, message="Name too long")])
    link = StringField("Link", validators=[DataRequired(), URL(message="Link must be a url")])
    description = TextAreaField("Description", validators=[Length(max=4096, message="Description too long"), Optional()])
    appid = HiddenField("app id", validators=[DataRequired()])
    catid = HiddenField("cat id", validators=[DataRequired()])

class SearchForm(Form):
    search = StringField("Search")

appcenter/forms.py
from flask_wtf import Form
from wtforms import StringField

class SearchForm(Form):
    search = StringField("Search")

appcenter/__init__.py
import datetime

from flask import Flask
from flask_security import Security, SQLAlchemyUserDatastore
from flask_mail import Mail
from flask_admin import Admin
from flask_admin.menu import MenuLink

from appcenter.database import *
from appcenter.adminviews import *
from appcenter.blueprints.app_center import appcenter_blueprint
from appcenter.blueprints.app_center.database import *
from appcenter.forms import SearchForm

app = Flask(__name__)
app.config.from_pyfile('appcenter.cfg')
db.init_app(app)

# Setup Flask-Security
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

## Mail
mail = Mail(app)

## Blueprints
app.register_blueprint(appcenter_blueprint)

## Admin interfaces
admin = Admin(app, name="App Center Admin", template_mode="bootstrap3", index_view=SecureAdminIndexView())
admin.add_link(MenuLink(name="Back", category='', url="/"))
admin.add_view(AppView(App, db.session, endpoint="appsadmin"))
admin.add_view(DocumentsView(Documents, db.session))
admin.add_view(CategoryView(Category, db.session))
admin.add_view(HostedView(Hosted, db.session))
admin.add_view(UserView(User, db.session))
admin.add_view(RoleView(Role, db.session))

@app.context_processor
def templatevariables():
    categories = Category.query.order_by(Category.weight).all()
    searchform = SearchForm()
    return dict(categories=categories, searchform=searchform)

# Create first user
@app.before_first_request
def create_user():
    db.create_all()
    if len(User.query.all()) == 0:
        print("Adding default user")
        try:
            user_datastore.create_user(email='admin@example.com', password='password', confirmed_at=datetime.datetime.now())
        except IntegrityError:
            pass
        user_datastore.find_or_create_role(name="admin", description="Admin Users")
        user_datastore.add_role_to_user("admin@example.com", "admin")
        category = Category(name="Other", description="Misc apps", weight=1000)
        db.session.add(category)
        internal = Hosted(name="Internal", description="Internally hosted apps", color="#1ca001")
        external = Hosted(name="External", description="Externally hosted apps", color="#b20002")
        db.session.add(internal)
        db.session.add(external)

    db.session.commit()

appcenter/blueprints/app_center/__init__.py
import json

from .database import *
from .forms import *
from flask import Blueprint

appcenter_blueprint = Blueprint('app_center', __name__, template_folder="templates")

from .views import *

appcenter/blueprints/app_center/views.py
import json

from . import appcenter_blueprint
from .database import *
from .forms import *
from flask import render_template, redirect, flash, url_for, request, abort
from flask_security import login_required
from sqlalchemy.exc import IntegrityError

@appcenter_blueprint.route("/")
@login_required
def index():
    firstCat = Category.query.order_by(Category.weight).first()
    return redirect(url_for('.getApps', id=firstCat.id))

@appcenter_blueprint.route("/search/<terms>")
@login_required
def search(terms):
    query = "%{0}%".format(terms)
    response = {"apps":[], "docs":[]}
    response["terms"] = terms
    apps = App.query.filter( (App.name.like(query)) | (App.description.like(query)) ).all()
    docs = Documents.query.filter( (Documents.name.like(query)) | (Documents.description.like(query)) ).all()
    for each in apps:
        response["apps"].append(dict(name=each.name, description=each.description, link=each.link))
    for each in docs:
        response["docs"].append(dict(name=each.name, description=each.description, link=each.link))
    return json.dumps(response)

@appcenter_blueprint.route("/cat/<int:id>")
@login_required
def getApps(id):
    apps = App.query.filter_by(category_id=id).all()
    adddocument = AddDocumentForm()
    return render_template('apps.html', adddocument=adddocument, apps=apps)

@appcenter_blueprint.route("/documents/<int:id>")
@login_required
def getDocumentation(id):
    documents = Documents.query.filter_by(app_id=id)
    app = App.query.filter_by(id=id).first()
    return render_template('docs_list.html', id=id, catid=app.category_id, documents=documents)

@appcenter_blueprint.route("/documents/add", methods=["POST"])
@login_required
def addDocumentation():
    adddocument = AddDocumentForm()
    response = {"messages": []}
    if adddocument.validate_on_submit():
        newdocument = Documents(name=adddocument.name.data, description=adddocument.description.data, link=adddocument.link.data, app_id=adddocument.appid.data)
        try:
            db.session.add(newdocument)
            db.session.commit()
        except IntegrityError:
            response["status"] = "error"
            response["messages"].append({"name":"name", "error": "Name already exists"})
        else:
            flash("Documentation added", "success")
            response["status"] = "success"
            response["messages"].append({"action": "redirect", "location":url_for('.getApps', id=adddocument.catid.data)})
    else:
        response["status"] = "error"
        for field in adddocument:
            for error in field.errors:
                response["messages"].append({"name":field.name, "error":error})
    return json.dumps(response)

appcenter/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>{% block title %}App Center{% endblock %}</title>
        {# <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.png') }}"> #}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css" integrity="sha384-2hfp1SzUoho7/TsGGGDaFdsuuDL0LX2hnUp6VkX3CUQ2K4K+xjboZdsXyp4oUHZj" crossorigin="anonymous">
        <link rel="stylesheet" href="/static/css/font-awesome.min.css">
        <link rel="stylesheet" href="/static/css/site.css">
        {% block head_js %}{% endblock %}
    </head>
    <body>
        <div class="container-fluid">
            {% if current_user.is_authenticated %}
            <div class="row">
                <div class="col-md-2 p-t-1" id="navbar">
                    {% block nav %}
                    <form class="form p-b-1" id="searchform">
                            {{ searchform.search(placeholder=searchform.search.label.text, class="form-control") }}
                    </form>
                    <ul class="nav nav-pills nav-stacked">
                        {% for category in categories %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('app_center.getApps', id=category.id) }}">{{ category.name }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                    <div id="bottomnav" class="col-md-12" role="group">
                        {% if current_user.has_role('admin') %}
                        <a class="btn bottomnavbutton" role="button" href="{{ url_for('appsadmin.create_view') }}"><i class="fa fa-plus"></i></a>
                        <a class="btn bottomnavbutton" role="button"  href="/admin/"><i class="fa fa-cogs" aria-hidden="true"></i></a>
                        {% endif %}
                        <a class="btn bottomnavbutton" role="button" href="{{ url_for_security('change_password') }}"><i class="fa fa-user" aria-hidden="true"></i></a>
                        <a class="btn bottomnavbutton" role="button"  href="{{ url_for_security('logout') }}"><i class="fa fa-sign-out" aria-hidden="true"></i></a>
                    </div>
                    {% endblock nav %}
                </div>
                <div class="col-md-10 offset-md-2">
                {% else %}
                <div class="col-md-12">
                {% endif %}
                    {% block messages %}
                    {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                    <div id="alerts" class="container-fluid">
                        <div class="row">
                    {% for category, message in messages %}
                            <div class="alert alert-dismissible alert-{{ category }} alert-message fade in" role="alerts">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                {{ message }}
                            </div>
                    {% endfor %}
                        </div>
                    </div>
                    {% endif %}
                    {% endwith %}
                    {% endblock %}
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
        {% block javascript %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/js/bootstrap.min.js" integrity="sha384-VjEeINv9OSwtWFLAtmc4JCtEJXXBub00gtSnszmspDLCtC0I4z4nqz7rEFbIZLLU" crossorigin="anonymous"></script>
        {% endblock %}
    </body>
</html>

appcenter/templates/macros.html
{% macro with_error_tooltip(field, label=True, size='col-md-3 col-xs-6') %} 
{% if field.errors %} 
{% set wrapperclass = size + ' has-danger' %} 
{% else %} 
{% set wrapperclass = size %} 
{% endif %} 
<div class="{{ wrapperclass }}"> 
    {% if label %} 
    {% set labelSize = kwargs.pop('labelSize', '') %} 
    {{ field.label(class="form-control-label") }} 
    {% endif %} 
    {% if field.errors %} 
    {% set _dummy = kwargs.update({'data-toggle':'tooltip', 'data-placement':'top', 'data-container':'body', 'title':field.errors[0]}) %} 
    {{ field(**kwargs) }} 
    {% else %} 
        {{ field(**kwargs) }} 
    {% endif %} 
</div> 
{% endmacro %} 

appcenter/templates/security/change_password.html
{% extends "layout.html" %}
{% from "macros.html" import with_error_tooltip %}
{% block content %}
<div class="container" id="content">
    <div class="row p-t-2">
        <div class="col-xs-12 col-md-6 offset-md-3">
            <div class="card card-block">
                <h1 class="card-title">Change Password</h1>
                <div class="card-text">
                <form action="{{ url_for_security('change_password') }}" method="POST">
                    <div class="row">
                        {{ with_error_tooltip(change_password_form.password, required=True, class="form-control", size="col-xs-12") }}
                    </div>
                    <div class="row">
                        {{ with_error_tooltip(change_password_form.new_password, required=True, class="form-control", size="col-xs-12") }}
                    </div>
                    <div class="row">
                        {{ with_error_tooltip(change_password_form.new_password_confirm, required=True, class="form-control", size="col-xs-12") }}
                    </div>
                    <div class="row p-t-1">
                        <div class="col-xs-12">
                            {{ change_password_form.submit(class="btn btn-primary btn-block") }}
                        </div>
                    </div>
                    {{ change_password_form.hidden_tag() }}
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

appcenter/templates/security/forgot_password.html
{% extends "layout.html" %}
{% from "macros.html" import with_error_tooltip %}
{% block content %}
<div class="container" id="content">
    <div class="row p-t-2">
        <div class="col-xs-12 col-md-6 offset-md-3">
            <div class="card card-block">
                <h1 class="card-title">Forgot Password</h1>
                <div class="card-text">
                <form action="{{ url_for_security('forgot_password') }}" method="POST">
                    <div class="row">
                        {{ with_error_tooltip(forgot_password_form.email, required=True, class="form-control", size="col-xs-12") }}
                    </div>
                    <div class="row p-t-1">
                        <div class="col-xs-12">
                            {{ forgot_password_form.submit(class="btn btn-primary btn-block") }}
                        </div>
                    </div>
                    {{ forgot_password_form.hidden_tag() }}
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

appcenter/templates/security/login_user.html
{% extends "layout.html" %}
{% from "macros.html" import with_error_tooltip %}
{% block content %}
<div class="container" id="content">
    <div class="row" id="login-row">
        <div class="col-xs-12 col-md-6 offset-md-3 p-t-2" id="login">
            <div class="card card-block">
                <h1 class="card-title">Login</h1>
                <p class="card-text">Enter your credentials below</p>
                <form action="{{ url_for_security('login') }}" method="POST">
                    <div class="row">
                        {{ with_error_tooltip(login_user_form.email, label=False, placeholder=login_user_form.email.label.text, class="form-control", size="col-xs-12") }}
                    </div>
                    <div class="row p-t-1">
                        {{ with_error_tooltip(login_user_form.password, label=False, placeholder=login_user_form.password.label.text, class="form-control", size="col-xs-12") }}
                    </div>
                    <div class="row p-t-1">
                        <div class="checkbox col-xs-12 text-xs-center">
                            <label>
                                {{ login_user_form.remember }} Remember Me  
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            {{ login_user_form.submit(class="btn btn-primary btn-block") }}
                        </div>
                    </div>
                    {{ login_user_form.hidden_tag() }}
                </form>
                {% if config["SECURITY_RECOVERABLE"] %}
                <p class="card-text">
                    <a href="{{ url_for_security('forgot_password') }}">Forgot Password?</a></br>
                </p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}